// <auto-generated />
using System;
using LoginovaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoginovaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoginovaAPI.Models.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidad_tipo");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("text")
                        .HasColumnName("valores_anteriores");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("text")
                        .HasColumnName("valores_nuevos");

                    b.HasKey("Id");

                    b.ToTable("auditoria_logs", (string)null);
                });

            modelBuilder.Entity("LoginovaAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Correo")
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nit")
                        .HasColumnType("text")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("LoginovaAPI.Models.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_foto");

                    b.Property<int>("RecogidaId")
                        .HasColumnType("integer")
                        .HasColumnName("recogida_id");

                    b.HasKey("Id");

                    b.HasIndex("RecogidaId");

                    b.ToTable("evidencias", (string)null);
                });

            modelBuilder.Entity("LoginovaAPI.Models.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNuevo")
                        .HasColumnType("text")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<int>("RecogidaId")
                        .HasColumnType("integer")
                        .HasColumnName("recogida_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("RecogidaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_estados", (string)null);
                });

            modelBuilder.Entity("LoginovaAPI.Models.Ingreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<int>("RecogidaId")
                        .HasColumnType("integer")
                        .HasColumnName("recogida_id");

                    b.Property<int>("ResponsableUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("responsable_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("RecogidaId");

                    b.HasIndex("ResponsableUsuarioId");

                    b.ToTable("ingresos", (string)null);
                });

            modelBuilder.Entity("LoginovaAPI.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("text")
                        .HasColumnName("datos_adicionales");

                    b.Property<bool>("Enviado")
                        .HasColumnType("boolean")
                        .HasColumnName("enviado");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_lectura");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean")
                        .HasColumnName("leido");

                    b.Property<int?>("RecogidaId")
                        .HasColumnType("integer")
                        .HasColumnName("recogida_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("notificaciones");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("permisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Crear nuevas recogidas",
                            Nombre = "crear_recogidas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Editar recogidas existentes",
                            Nombre = "editar_recogidas"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cambiar el estado de una recogida",
                            Nombre = "cambiar_estado_recogidas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Subir fotos y evidencia",
                            Nombre = "subir_evidencias"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Registrar dinero cobrado",
                            Nombre = "registrar_ingresos"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Ver control de ingresos",
                            Nombre = "ver_ingresos"
                        });
                });

            modelBuilder.Entity("LoginovaAPI.Models.Recogida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPaquetes")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_paquetes");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("DineroRecibido")
                        .HasColumnType("boolean")
                        .HasColumnName("dinero_recibido");

                    b.Property<string>("DireccionRecogida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion_recogida");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_programada");

                    b.Property<DateTime?>("FechaRecogida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recogida");

                    b.Property<string>("FormaPagoUltima")
                        .HasColumnType("text")
                        .HasColumnName("forma_pago_ultima");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric")
                        .HasColumnName("longitud");

                    b.Property<decimal?>("MontoCobrado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_cobrado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("recogidas", (string)null);
                });

            modelBuilder.Entity("LoginovaAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Control total del sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Realiza recogidas",
                            Nombre = "Operador"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Consulta servicios",
                            Nombre = "Cliente"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Gestiona operaciones con permisos limitados",
                            Nombre = "Subadministrador"
                        });
                });

            modelBuilder.Entity("LoginovaAPI.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("numeric")
                        .HasColumnName("latitud");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("numeric")
                        .HasColumnName("longitud");

                    b.Property<double>("PrecisionMetros")
                        .HasColumnType("double precision")
                        .HasColumnName("precision_metros");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<double?>("Velocidad")
                        .HasColumnType("double precision")
                        .HasColumnName("velocidad");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ubicaciones", (string)null);
                });

            modelBuilder.Entity("LoginovaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PermisosJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permisos_json");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Correo = "admin@loginova.com",
                            FechaCreacion = new DateTime(2026, 7, 4, 1, 45, 8, 78, DateTimeKind.Utc).AddTicks(5873),
                            Nombre = "Administrador",
                            Password = "pbkdf2$100000$Mz5H5D/HLBMh8XJpehefgg==$oHa6c+5jiazyNL+1zbvpvCdxS1xssd0yi1JSLFwh3nU=",
                            PermisosJson = "[]",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("LoginovaAPI.Models.Evidencia", b =>
                {
                    b.HasOne("LoginovaAPI.Models.Recogida", "Recogida")
                        .WithMany("Evidencias")
                        .HasForeignKey("RecogidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recogida");
                });

            modelBuilder.Entity("LoginovaAPI.Models.HistorialEstado", b =>
                {
                    b.HasOne("LoginovaAPI.Models.Recogida", "Recogida")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("RecogidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoginovaAPI.Models.Usuario", "Usuario")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Recogida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Ingreso", b =>
                {
                    b.HasOne("LoginovaAPI.Models.Cliente", "Cliente")
                        .WithMany("Ingresos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoginovaAPI.Models.Recogida", "Recogida")
                        .WithMany("Ingresos")
                        .HasForeignKey("RecogidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoginovaAPI.Models.Usuario", "ResponsableUsuario")
                        .WithMany("IngresosRecibidos")
                        .HasForeignKey("ResponsableUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Recogida");

                    b.Navigation("ResponsableUsuario");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Notificacion", b =>
                {
                    b.HasOne("LoginovaAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Recogida", b =>
                {
                    b.HasOne("LoginovaAPI.Models.Cliente", "Cliente")
                        .WithMany("Recogidas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoginovaAPI.Models.Usuario", "Usuario")
                        .WithMany("Recogidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Ubicacion", b =>
                {
                    b.HasOne("LoginovaAPI.Models.Usuario", "Usuario")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Usuario", b =>
                {
                    b.HasOne("LoginovaAPI.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Cliente", b =>
                {
                    b.Navigation("Ingresos");

                    b.Navigation("Recogidas");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Recogida", b =>
                {
                    b.Navigation("Evidencias");

                    b.Navigation("HistorialEstados");

                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LoginovaAPI.Models.Usuario", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("IngresosRecibidos");

                    b.Navigation("Recogidas");

                    b.Navigation("Ubicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
